version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - 25665:25565
    environment:
      EULA: "TRUE"
      TYPE: "CATSERVER"
      VERSION: 1.12.2
      MEMORY: "4G"
      OPS: Egor_BRO100
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data